import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10.5

[font.normal]
family = "BlexMono Nerd Font"
style = "Medium"
# family = "Noto Sans Mono"
# style = "Medium"

[font.offset]
x = 0
y = 0

[window]
decorations = "buttonless"
